var parser = require("./parser2.js").parser;
var walkerLib = require("./TreeWalker.js");
console.log(parser);
// parser.parse("if 3 == 3: var hola = 2 endif");
//var root = parser.parse("$QUESO = 1 $PEDO = 2 if $PEDO == 1: $QUESO = 2 endif");
var root = parser.parse("mover 30, 20, 4 mover 20, 30, 2");
var onComplete = function() { return true; };
var walker = new walkerLib.TreeWalker(root, onComplete);
walker.childWalk();
walker.childWalk();
walker.childWalk();
walker.childWalk();
walker.childWalk();
walker.childWalk();
walker.childWalk();
walker.childWalk();
walker.childWalk();
walker.childWalk();
walker.childWalk();
walker.childWalk();
walker.childWalk();
walker.childWalk();